//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Arithmetic.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ArithmeticParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IArithmeticListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArithmeticParser.file_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_([NotNull] ArithmeticParser.File_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArithmeticParser.file_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_([NotNull] ArithmeticParser.File_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArithmeticParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ArithmeticParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArithmeticParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ArithmeticParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArithmeticParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] ArithmeticParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArithmeticParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] ArithmeticParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArithmeticParser.scientific"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScientific([NotNull] ArithmeticParser.ScientificContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArithmeticParser.scientific"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScientific([NotNull] ArithmeticParser.ScientificContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArithmeticParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] ArithmeticParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArithmeticParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] ArithmeticParser.VariableContext context);
}
