//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Arithmetic.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ArithmeticLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		VARIABLE=1, SCIENTIFIC_NUMBER=2, LPAREN=3, RPAREN=4, PLUS=5, MINUS=6, 
		TIMES=7, DIV=8, GT=9, LT=10, EQ=11, POINT=12, POW=13, SEMI=14, WS=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"VARIABLE", "SCIENTIFIC_NUMBER", "LPAREN", "RPAREN", "PLUS", "MINUS", 
		"TIMES", "DIV", "GT", "LT", "EQ", "POINT", "POW", "SEMI", "WS", "VALID_ID_START", 
		"VALID_ID_CHAR", "NUMBER", "UNSIGNED_INTEGER", "E", "SIGN"
	};


	public ArithmeticLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ArithmeticLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "'('", "')'", "'+'", "'-'", "'*'", "'/'", "'>'", "'<'", 
		"'='", "'.'", "'^'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "VARIABLE", "SCIENTIFIC_NUMBER", "LPAREN", "RPAREN", "PLUS", "MINUS", 
		"TIMES", "DIV", "GT", "LT", "EQ", "POINT", "POW", "SEMI", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Arithmetic.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ArithmeticLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', 'y', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x30', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x33', '\v', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '\x38', '\n', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', '<', '\n', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x6', '\x10', 'W', '\n', '\x10', '\r', '\x10', 
		'\xE', '\x10', 'X', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x5', 
		'\x11', '^', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', 
		'\x62', '\n', '\x12', '\x3', '\x13', '\x6', '\x13', '\x65', '\n', '\x13', 
		'\r', '\x13', '\xE', '\x13', '\x66', '\x3', '\x13', '\x3', '\x13', '\x6', 
		'\x13', 'k', '\n', '\x13', '\r', '\x13', '\xE', '\x13', 'l', '\x5', '\x13', 
		'o', '\n', '\x13', '\x3', '\x14', '\x6', '\x14', 'r', '\n', '\x14', '\r', 
		'\x14', '\xE', '\x14', 's', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x2', '\x2', '\x17', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x2', '#', '\x2', '%', '\x2', '\'', 
		'\x2', ')', '\x2', '+', '\x2', '\x3', '\x2', '\x6', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', '-', '-', 
		'/', '/', '\x2', '{', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '-', '\x3', '\x2', '\x2', '\x2', '\x5', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\a', '=', '\x3', '\x2', '\x2', '\x2', '\t', '?', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x41', '\x3', '\x2', '\x2', '\x2', '\r', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'G', '\x3', '\x2', '\x2', '\x2', '\x13', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\x15', 'K', '\x3', '\x2', '\x2', '\x2', '\x17', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x19', 'O', '\x3', '\x2', '\x2', '\x2', '\x1B', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', 'S', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'V', '\x3', '\x2', '\x2', '\x2', '!', ']', '\x3', '\x2', '\x2', '\x2', 
		'#', '\x61', '\x3', '\x2', '\x2', '\x2', '%', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\'', 'q', '\x3', '\x2', '\x2', '\x2', ')', 'u', '\x3', '\x2', 
		'\x2', '\x2', '+', 'w', '\x3', '\x2', '\x2', '\x2', '-', '\x31', '\x5', 
		'!', '\x11', '\x2', '.', '\x30', '\x5', '#', '\x12', '\x2', '/', '.', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x31', '/', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '\x4', '\x3', '\x2', '\x2', '\x2', '\x33', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x34', ';', '\x5', '%', '\x13', '\x2', '\x35', 
		'\x37', '\x5', ')', '\x15', '\x2', '\x36', '\x38', '\x5', '+', '\x16', 
		'\x2', '\x37', '\x36', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\x38', '\x39', '\x3', '\x2', '\x2', '\x2', '\x39', 
		':', '\x5', '\'', '\x14', '\x2', ':', '<', '\x3', '\x2', '\x2', '\x2', 
		';', '\x35', '\x3', '\x2', '\x2', '\x2', ';', '<', '\x3', '\x2', '\x2', 
		'\x2', '<', '\x6', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '*', '\x2', 
		'\x2', '>', '\b', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '+', '\x2', 
		'\x2', '@', '\n', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '-', 
		'\x2', '\x2', '\x42', '\f', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', 
		'\a', '/', '\x2', '\x2', '\x44', '\xE', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\a', ',', '\x2', '\x2', '\x46', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'G', 'H', '\a', '\x31', '\x2', '\x2', 'H', '\x12', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'J', '\a', '@', '\x2', '\x2', 'J', '\x14', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'L', '\a', '>', '\x2', '\x2', 'L', '\x16', '\x3', '\x2', 
		'\x2', '\x2', 'M', 'N', '\a', '?', '\x2', '\x2', 'N', '\x18', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\a', '\x30', '\x2', '\x2', 'P', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'R', '\a', '`', '\x2', '\x2', 'R', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'T', '\a', '=', '\x2', '\x2', 'T', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'W', '\t', '\x2', '\x2', '\x2', 'V', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\x3', 
		'\x2', '\x2', '\x2', 'Z', '[', '\b', '\x10', '\x2', '\x2', '[', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\\', '^', '\t', '\x3', '\x2', '\x2', ']', '\\', 
		'\x3', '\x2', '\x2', '\x2', '^', '\"', '\x3', '\x2', '\x2', '\x2', '_', 
		'\x62', '\x5', '!', '\x11', '\x2', '`', '\x62', '\x4', '\x32', ';', '\x2', 
		'\x61', '_', '\x3', '\x2', '\x2', '\x2', '\x61', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '$', '\x3', '\x2', '\x2', '\x2', '\x63', '\x65', '\x4', 
		'\x32', ';', '\x2', '\x64', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 'g', 'n', '\x3', '\x2', 
		'\x2', '\x2', 'h', 'j', '\a', '\x30', '\x2', '\x2', 'i', 'k', '\x4', '\x32', 
		';', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\x3', '\x2', 
		'\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'o', '\x3', '\x2', '\x2', '\x2', 'n', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', '&', '\x3', '\x2', 
		'\x2', '\x2', 'p', 'r', '\x4', '\x32', ';', '\x2', 'q', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 's', 'q', '\x3', '\x2', 
		'\x2', '\x2', 's', 't', '\x3', '\x2', '\x2', '\x2', 't', '(', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'v', '\t', '\x4', '\x2', '\x2', 'v', '*', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'x', '\t', '\x5', '\x2', '\x2', 'x', ',', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x2', '\x31', '\x37', ';', 'X', ']', '\x61', '\x66', 
		'l', 'n', 's', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
